savedcmd_xbelite2_rust.o := OBJTREE=/usr/lib/modules/6.19.11-arch1-1/build RUST_MODFILE=./xbelite2 rustc --edition=2021 -Zbinary_dep_depinfo=y -Astable_features -Aunused_features -Dnon_ascii_idents -Dunsafe_op_in_unsafe_fn -Wmissing_docs -Wrust_2018_idioms -Wunreachable_pub -Wclippy::all -Wclippy::as_ptr_cast_mut -Wclippy::as_underscore -Wclippy::cast_lossless -Wclippy::ignored_unit_patterns -Wclippy::mut_mut -Wclippy::needless_bitwise_bool -Aclippy::needless_lifetimes -Wclippy::no_mangle_with_rust_abi -Wclippy::ptr_as_ptr -Wclippy::ptr_cast_constness -Wclippy::ref_as_ptr -Wclippy::undocumented_unsafe_blocks -Wclippy::unnecessary_safety_comment -Wclippy::unnecessary_safety_doc -Wrustdoc::missing_crate_level_docs -Wrustdoc::unescaped_backticks -Cpanic=abort -Cembed-bitcode=n -Clto=n -Cforce-unwind-tables=n -Ccodegen-units=1 -Csymbol-mangling-version=v0 -Crelocation-model=static -Zfunction-sections=n -Wclippy::float_arithmetic --target=/usr/lib/modules/6.19.11-arch1-1/build/scripts/target.json -Ctarget-feature=-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2 -Zcf-protection=branch -Cjump-tables=n -Ctarget-cpu=x86-64 -Ztune-cpu=generic -Cno-redzone=y -Ccode-model=kernel -Zfunction-return=thunk-extern -Zpatchable-function-entry=16,16 -Copt-level=2 -Cdebug-assertions=n -Coverflow-checks=y -Zdwarf-version=5 -Cdebuginfo=2  --cfg MODULE  @/usr/lib/modules/6.19.11-arch1-1/build/include/generated/rustc_cfg -Zallow-features=asm_const,asm_goto,arbitrary_self_types,lint_reasons,offset_of_nested,raw_ref_op,used_with_arg -Zcrate-attr=no_std -Zcrate-attr='feature(asm_const,asm_goto,arbitrary_self_types,lint_reasons,offset_of_nested,raw_ref_op,used_with_arg)' -Zunstable-options --extern pin_init --extern kernel --crate-type rlib -L /usr/lib/modules/6.19.11-arch1-1/build/rust/ --crate-name xbelite2_rust --sysroot=/dev/null --out-dir ./ --emit=dep-info=./.xbelite2_rust.o.d --emit=obj=xbelite2_rust.o xbelite2_rust.rs 

source_xbelite2_rust.o := xbelite2_rust.rs

deps_xbelite2_rust.o := \
  /usr/lib/modules/6.19.11-arch1-1/build/rust/libcore.rmeta \
  /usr/lib/modules/6.19.11-arch1-1/build/rust/libcompiler_builtins.rmeta \

xbelite2_rust.o: $(deps_xbelite2_rust.o)

$(deps_xbelite2_rust.o):
