PACKAGE_NAME="xbelite2-dkms"
PACKAGE_VERSION="0.3.3"
BUILT_MODULE_NAME[0]="xbelite2"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make -C ${kernel_source_dir} M=${source_tree} modules"
CLEAN[0]="make -C ${kernel_source_dir} M=${source_tree} clean"
